"""Orchestration: build the full synthetic dataset and write it to disk."""

from __future__ import annotations

import hashlib
import json
import logging
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from data_pipeline.synthetic.anomalies import count_inserted_rows, inject_anomalies
from data_pipeline.synthetic.config import GeneratorConfig
from data_pipeline.synthetic.customers import generate_customers
from data_pipeline.synthetic.ledger import build_ledger
from data_pipeline.synthetic.transactions import build_profiles, generate_normal, materialize
from data_pipeline.synthetic.validation import ValidationReport, validate_tables

logger = logging.getLogger(__name__)
GENERATOR_VERSION = "1.0.0"
SYNTHETIC_NOTICE = (
    "SYNTHETIC DATA. Generated by FIN-GUARD's data_pipeline.synthetic. Contains no real people, "
    "accounts or transactions. Performance measured on it says nothing about real bank data."
)


@dataclass
class SyntheticDataset:
    tables: dict[str, pd.DataFrame]
    manifest: dict[str, Any]
    validation: ValidationReport


def _stage_rngs(seed: int) -> list[np.random.Generator]:
    """One independent stream per stage so editing one stage never reshuffles the others."""
    return [np.random.default_rng(s) for s in np.random.SeedSequence(seed).spawn(5)]


def generate_dataset(cfg: GeneratorConfig) -> SyntheticDataset:
    rng_cust, rng_prof, rng_tx, rng_anom, rng_ledger = _stage_rngs(cfg.seed)

    customers, kyc, kyc_labels, entity_labels = generate_customers(cfg, rng_cust)
    profiles = build_profiles(customers, cfg, rng_prof)

    n_inserted = count_inserted_rows(cfg)
    normal = generate_normal(profiles, cfg.n_transactions - n_inserted, cfg, rng_tx)
    raw, realised = inject_anomalies(normal, profiles, cfg, rng_anom)
    tx = materialize(raw, profiles).sort_values("timestamp", kind="stable").reset_index(drop=True)
    tx.insert(0, "transaction_id", [f"TXN-{i:08d}" for i in range(len(tx))])
    tx["reference_id"] = [f"REF-{i:010d}" for i in range(len(tx))]
    tx["is_synthetic"] = True

    transaction_labels = pd.DataFrame(
        {
            "transaction_id": tx["transaction_id"],
            "is_anomaly": tx["anomaly_type"] != "",
            "anomaly_type": tx["anomaly_type"].replace("", "none"),
            "episode_id": tx["episode_id"],
        }
    )
    tx = tx.drop(columns=["anomaly_type", "episode_id"])
    ledger, ledger_labels = build_ledger(tx, cfg, rng_ledger)

    tables = {
        "customers": customers,
        "kyc_records": kyc,
        "transactions": tx,
        "ledger": ledger,
        "transaction_labels": transaction_labels,
        "ledger_labels": ledger_labels,
        "kyc_labels": kyc_labels,
        "entity_labels": entity_labels,
    }
    report = validate_tables(tables, cfg)
    manifest = {
        "notice": SYNTHETIC_NOTICE,
        "generator_version": GENERATOR_VERSION,
        "config": json.loads(cfg.model_dump_json()),
        "counts": {name: len(df) for name, df in tables.items()},
        "anomaly_rows_by_type": realised,
        "anomaly_rate_realised": float(transaction_labels["is_anomaly"].mean()),
        "ledger_discrepancies_by_type": ledger_labels["discrepancy_type"].value_counts().to_dict(),
        "kyc_variations_by_type": kyc_labels["variation_type"].value_counts().to_dict(),
        "entity_relations": entity_labels["relation"].value_counts().to_dict(),
        "validation": {"ok": report.ok, "checks_run": report.checks_run, "errors": report.errors},
    }
    return SyntheticDataset(tables=tables, manifest=manifest, validation=report)


def write_dataset(dataset: SyntheticDataset, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    hashes: dict[str, str] = {}
    for name, df in dataset.tables.items():
        path = out_dir / f"{name}.csv"
        df.to_csv(path, index=False)
        hashes[path.name] = hashlib.sha256(path.read_bytes()).hexdigest()
    manifest = {**dataset.manifest, "file_sha256": hashes}
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2, default=str))
    (out_dir / "SYNTHETIC_DATA_NOTICE.txt").write_text(SYNTHETIC_NOTICE + "\n")
    logger.info("wrote %d tables to %s", len(dataset.tables), out_dir)
