"""Static reference tables for synthetic generation. All values are invented / illustrative."""

FIRST_NAMES = [
    "Mohammed",
    "Alexander",
    "Sergey",
    "Yuri",
    "Ekaterina",
    "Robert",
    "Elizabeth",
    "Christopher",
    "Catherine",
    "Michael",
    "Priya",
    "Arjun",
    "Wei",
    "Li",
    "Hans",
    "Anna",
    "Maria",
    "John",
    "Emma",
    "Oliver",
    "Sophie",
    "Lucas",
    "Fatima",
    "Omar",
    "Aisha",
    "Rahul",
    "Neha",
    "Daniel",
    "Sarah",
    "David",
    "Laura",
    "Thomas",
    "Julia",
    "Pierre",
    "Camille",
    "Kenji",
    "Mei",
    "Amit",
    "Sunita",
    "William",
    "Grace",
    "Henry",
    "Olivia",
    "Noah",
    "Ava",
    "James",
    "Isabel",
    "Carlos",
]
FIRST_NAME_VARIANTS = {
    "Mohammed": ["Muhammad", "Mohamed", "Mohammad"],
    "Alexander": ["Aleksandr", "Alexandr", "Alexandre"],
    "Sergey": ["Sergei", "Serguei"],
    "Yuri": ["Yury", "Iurii"],
    "Ekaterina": ["Yekaterina", "Katerina"],
    "Robert": ["Rob", "Bobby"],
    "Elizabeth": ["Elisabeth", "Liz"],
    "Christopher": ["Kristopher", "Chris"],
    "Catherine": ["Katherine", "Kathryn"],
    "Michael": ["Mikhail", "Micheal"],
    "Aisha": ["Aysha", "Ayesha"],
    "Fatima": ["Fatimah", "Fatema"],
}

LAST_NAMES = [
    "Smith",
    "Schmidt",
    "Kowalski",
    "Ivanov",
    "Hussain",
    "Zhang",
    "Chaudhary",
    "Mueller",
    "Patel",
    "Singh",
    "Johnson",
    "Brown",
    "Wilson",
    "Taylor",
    "Anderson",
    "Thomas",
    "Moore",
    "Martin",
    "Clark",
    "Lewis",
    "Walker",
    "Hall",
    "Young",
    "King",
    "Wright",
    "Lopez",
    "Hill",
    "Scott",
    "Green",
    "Adams",
    "Baker",
    "Nelson",
    "Carter",
    "Mitchell",
    "Roberts",
    "Turner",
    "Phillips",
    "Campbell",
    "Parker",
    "Evans",
    "Edwards",
    "Collins",
    "Stewart",
    "Sanchez",
    "Morris",
    "Rogers",
    "Reed",
    "Cook",
    "Morgan",
    "Bell",
]
LAST_NAME_VARIANTS = {
    "Smith": ["Smyth", "Smythe"],
    "Schmidt": ["Schmitt", "Schmid"],
    "Kowalski": ["Kovalsky", "Kowalsky"],
    "Ivanov": ["Ivanoff", "Ivanow"],
    "Hussain": ["Hussein", "Husain", "Hossain"],
    "Zhang": ["Chang", "Cheung"],
    "Chaudhary": ["Choudhury", "Chowdhury"],
    "Mueller": ["Muller", "Mueler"],
    "Patel": ["Patell"],
    "Singh": ["Sing"],
}

STREETS = [
    "Oak",
    "Maple",
    "Cedar",
    "Elm",
    "Pine",
    "Lake",
    "Hill",
    "River",
    "Park",
    "Church",
    "Station",
    "Market",
    "Garden",
    "Mill",
    "High",
    "Bridge",
    "Sunset",
    "Forest",
    "Meadow",
    "Spring",
]
STREET_SUFFIXES = ["Street", "Road", "Avenue", "Lane", "Drive"]

# (country code, sampling weight)
HOME_COUNTRIES: list[tuple[str, float]] = [
    ("US", 0.30),
    ("GB", 0.12),
    ("DE", 0.10),
    ("IN", 0.20),
    ("AE", 0.05),
    ("SG", 0.05),
    ("CA", 0.06),
    ("AU", 0.06),
    ("FR", 0.06),
]
CITIES = {
    "US": ["Springfield", "Riverton", "Fairview", "Lakewood"],
    "GB": ["Ashford", "Kingsbury", "Northwick", "Eastleigh"],
    "DE": ["Neustadt", "Bergheim", "Altenau", "Weidenau"],
    "IN": ["Rampur", "Nagarpur", "Vijaypur", "Shantinagar"],
    "AE": ["Al Noor", "Marina Bay", "Sunrise City", "Palm Court"],
    "SG": ["Tanjong", "Bukit Lama", "Kampong Baru", "Marina East"],
    "CA": ["Maplewood", "Pinehurst", "Rivercrest", "Lakeshore"],
    "AU": ["Bayview", "Redhill", "Coastdale", "Northgate"],
    "FR": ["Beaulieu", "Montclair", "Rivedor", "Saint-Aubin"],
}
CURRENCY_BY_COUNTRY = {
    "US": "USD",
    "GB": "GBP",
    "DE": "EUR",
    "IN": "INR",
    "AE": "AED",
    "SG": "SGD",
    "CA": "CAD",
    "AU": "AUD",
    "FR": "EUR",
}
# Illustrative constants ONLY (not market data): units of currency per 1 USD.
UNITS_PER_USD = {
    "USD": 1.0,
    "GBP": 0.8,
    "EUR": 0.92,
    "INR": 83.0,
    "AED": 3.67,
    "SGD": 1.35,
    "CAD": 1.36,
    "AUD": 1.5,
}
# Destinations that are unusual relative to any customer's home country.
UNUSUAL_COUNTRIES = ["BR", "ZA", "TR", "MX", "KY", "PA", "CY", "MT", "VN", "ID"]

# Typical single-transaction size in USD-equivalent.
OCCUPATIONS = {
    "teacher": 120.0,
    "software engineer": 220.0,
    "nurse": 130.0,
    "shop owner": 300.0,
    "consultant": 260.0,
    "driver": 90.0,
    "physician": 340.0,
    "student": 50.0,
    "retired": 100.0,
    "accountant": 180.0,
}
ACCOUNT_TYPE_MULTIPLIER = {"personal": 1.0, "business": 4.0, "savings": 1.5}
